Repository Britva1910/project-management-app, pull requests merged in 2022-11, with the labels that each got.

#84 Add adaptive 404 page
  src/app/dialog/dialog.module.ts
  src/app/pages/board-page/board-page.component.scss
  src/app/pages/board-page/board-page.module.ts
  src/app/pages/board-page/components/edit-task/edit-task.component.html
  src/app/pages/board-page/services/edit-task.service.ts
  src/app/pages/board-page/store/state-board.ts
  src/app/pages/main-page/components/board-list/board-list.component.html
  src/app/pages/welcome-page/components/teammate-card/teammate.component.scss
  src/app/pages/welcome-page/welcome-page.component.scss
  src/app/pages/welcome-page/welcome-page.module.ts
  src/app/shared/components/not-found-pages/not-found-pages.component.scss
  src/app/shared/interceptors/spinner.interceptor.spec.ts
  src/app/shared/interceptors/spinner.interceptor.ts
  src/assets/fonts/Poppinsregular.ttf
  src/assets/fonts/Poppinsregular.woff
  src/assets/fonts/Poppinsregular.woff2
  src/assets/fonts/inglobal.ttf
  src/assets/fonts/inglobalb.ttf
  src/assets/fonts/title.ttf
  src/assets/i18n/en.json
  src/assets/i18n/ru.json
  src/assets/img/Frame 41.png
  src/styles/fonts.scss
  src/styles/mixins.scss
Labels: enhancement

#83 82 fix edit profile
  src/app/pages/auth-page/services/login.service.ts
  src/app/pages/welcome-page/components/teammate-card/teammate.component.html
  src/app/pages/welcome-page/components/teammate-card/teammate.component.scss
  src/app/pages/welcome-page/services/edit-profile.service.ts
  src/app/pages/welcome-page/welcome-page.component.ts
  src/app/shared/components/edit-profile/edit-profile.component.ts
  src/app/shared/constant/team-data.ts
  src/app/shared/guards/auth.guard.ts
  src/app/shared/interceptors/header-add-tokken.interceptor.ts
  src/app/shared/services/local-storage-service/local-storage.service.ts
  src/app/shared/services/notification-service/notification.service.ts
  src/app/shared/store/app.action.ts
  src/app/shared/store/app.reducer.ts
  src/assets/i18n/en.json
  src/assets/i18n/ru.json
  src/assets/img/IL-avatar.png
  src/assets/img/SM-avatar.png
  src/assets/img/UD-avatar.jpg
Labels: bug, enhancement, Welcom page

#85 Delete bag=> edit-board-modal
  src/app/pages/board-page/board-page.module.ts
  src/app/pages/board-page/components/board-container/board-container.component.html
  src/app/pages/board-page/components/board-container/board-container.component.scss
  src/app/pages/board-page/components/drag-handle-column/drag-handle-column.component.html
  src/app/pages/board-page/components/drag-handle-column/drag-handle-column.component.scss
  src/app/pages/board-page/components/drag-handle-column/drag-handle-column.component.spec.ts
  src/app/pages/board-page/components/drag-handle-column/drag-handle-column.component.ts
  src/app/pages/main-page/components/board-list/board-list.component.scss
  src/app/pages/main-page/components/edit-modal/edit-modal.component.html
  src/assets/i18n/en.json
  src/assets/i18n/ru.json
Labels: bug
